#!/usr/bin/env bash
# comment
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo sed -i 's,pid /run/nginx.pid,pid /run/nginx.bak,'/etc/nginx/nginx.conf
